'use client';

import Link from 'next/link';
import { industries, processSteps, resources, solutionServices } from '@/lib/content';
import { catalogueCategories } from '@/lib/catalogue';
import { useRFQ } from './SiteShell';

const basePath = process.env.NEXT_PUBLIC_BASE_PATH || '';
const assetUrl = path => `${basePath}${path}`;

export function CompanyPage() {
  return <><section className="standard-hero company-hero" style={{ backgroundImage: `linear-gradient(90deg,rgba(13,23,20,.94),rgba(13,23,20,.5)),url(${assetUrl('/assets/industry/refining.jpg')})` }}><p className="eyebrow light">COMPANY / IKINOVAC GLOBAL</p><h1>ENGINEERING<br /><em>IN MOTION.</em></h1><p>A company story shaped around technical clarity, global capability and accountable project support.</p></section><section id="company-story" className="company-page-story"><div><p className="eyebrow">IKINOVAC / OUR APPROACH</p><h2>Made for the<br /><em>critical details.</em></h2></div><div><p>IKINOVAC Global brings industrial product knowledge, procurement coordination and a connected supply conversation into one practical route for the project team.</p><p>We start with what is known, surface what needs attention, and keep the technical and commercial context close to the requirement.</p><Link href="/contact" className="text-arrow">Start a conversation <span>→</span></Link></div></section><section id="company-principles" className="company-principles">{[['01','Engineering expertise','A disciplined starting point for technical product and project conversations.'],['02','Global capability','Supply coordination designed around the requirement and destination.'],['03','Quality context','Documentation and quality requirements considered in the working brief.'],['04','Customer focus','A responsive route to the details that help projects move forward.']].map(([number,title,copy]) => <article key={number}><b>{number}</b><h3>{title}</h3><p>{copy}</p></article>)}</section></>;
}

export function IndustriesPage() {
  const hero = industries[0];
  return <><section className="standard-hero industries-hero" style={{ backgroundImage: `linear-gradient(115deg,rgba(13,23,20,.96),rgba(13,23,20,.45)),url(${assetUrl(hero.image)})` }}><p className="eyebrow light">INDUSTRIES / APPLICATION CONTEXT</p><h1>BUILT TO OPERATE<br /><em>WHERE IT COUNTS.</em></h1><p>Industrial context changes the questions. We structure the product and project conversation around it.</p></section><section className="industry-page-grid">{industries.map(industry => <Link href={`/contact?industry=${encodeURIComponent(industry.name)}`} key={industry.name} id={`industry-${industry.id}`} aria-label={`${industry.name}: ${industry.imageAlt}`} style={{ backgroundImage: `linear-gradient(180deg,rgba(13,23,20,.1),rgba(13,23,20,.88)),url(${assetUrl(industry.image)})` }}><b>{industry.number}</b><h2>{industry.name}</h2><p>{industry.description}</p><span>Discuss applicable product families →</span></Link>)}</section><section className="industry-note"><p className="eyebrow">REQUIREMENTS-LED</p><h2>Tell us the industry context. <em>We&apos;ll start with the relevant questions.</em></h2><Link href="/contact" className="button button-dark">Start an enquiry <span>→</span></Link></section></>;
}

export function SolutionsPage() {
  return <><section className="standard-hero solutions-hero" style={{ backgroundImage: `linear-gradient(90deg,rgba(13,23,20,.94),rgba(13,23,20,.45)),url(${assetUrl('/assets/industry/procurement.jpg')})` }}><p className="eyebrow light">SOLUTIONS / CONNECTED DELIVERY</p><h1>MOVE THE<br /><em>REQUIREMENT</em><br />FORWARD.</h1><p>A connected route from technical review through supply coordination and delivery context.</p></section><section className="solution-service-list">{solutionServices.map(service => <article key={service.number}><b>{service.number}</b><h2>{service.title}</h2><p>{service.description}</p><span>↗</span></article>)}</section><section className="process-timeline"><div><p className="eyebrow light">PROJECT FLOW / 08 STEPS</p><h2>One clear<br /><em>project path.</em></h2></div><ol>{processSteps.map((step, index) => <li key={step}><b>{String(index + 1).padStart(2, '0')}</b><span>{step}</span></li>)}</ol></section><section className="inline-cta"><p className="eyebrow">READY TO START?</p><h2>Bring the brief.<br /><em>We&apos;ll bring the route.</em></h2><Link href="/contact" className="button button-dark">Discuss a requirement <span>→</span></Link></section></>;
}

export function GlobalPresencePage() {
  return <><section className="presence-hero"><p className="eyebrow light">GLOBAL PRESENCE / CAPABILITY</p><h1>CONNECTED<br />ACROSS <em>GLOBAL</em><br />PROJECTS.</h1><p>IKINOVAC supports global sourcing and international project requirements. The map shows supply-network regions, not unverified office locations.</p><div className="presence-map" aria-label="Illustrative global supply-network map"><svg className="world-map" viewBox="0 0 1000 470" role="img" aria-label="World map showing supply network regions"><g className="world-land"><path d="M77 107l39-34 82-11 68 22 23 32-18 29-42 6-27 24-46-4-20 25-38-20-8-34z" /><path d="M236 205l34 13 18 46-14 39 9 63-24 72-23-39 2-65-19-48 9-42z" /><path d="M432 101l38-22 41 9 13 20-26 17-34 0-32 21-24-15z" /><path d="M467 151l46 8 29 42-5 71-27 59-33-17-15-63-25-39 8-42z" /><path d="M532 109l60-32 107 12 77 37 72 5 26 35-35 22-61-10-42 30-58-8-40 27-82-26-34-37z" /><path d="M742 256l39 7 33 27-11 31-45-1-23-29z" /><path d="M775 351l28-12 34 18-4 25-42 6-25-16z" /><path d="M103 75l26-26 25 8-13 22-25 8z" /></g><g className="world-routes"><path d="M182 130C305 83 425 119 492 157S669 123 765 164" /><path d="M257 285C341 245 413 235 490 226S662 279 776 274" /><path d="M493 157C516 204 505 231 492 267" /></g></svg><i className="map-point point-na" aria-label="North America network region" /><i className="map-point point-sa" aria-label="South America network region" /><i className="map-point point-eu" aria-label="Europe network region" /><i className="map-point point-af" aria-label="Africa network region" /><i className="map-point point-as" aria-label="Asia network region" /><i className="map-point point-oc" aria-label="Oceania network region" /></div></section><section className="presence-statements">{['Global sourcing network', 'International project support', 'Multi-region supply'].map((item, index) => <article key={item}><b>0{index + 1}</b><h2>{item}</h2><p>Discuss the sourcing, delivery and project context with the IKINOVAC project desk.</p></article>)}</section></>;
}

export function ResourcesPage() {
  return <><section className="resource-hero" style={{ backgroundImage: `linear-gradient(105deg,rgba(13,23,20,.96),rgba(13,23,20,.55)),url(${assetUrl('/assets/industry/instrumentation.jpg')})` }}><p className="eyebrow light">RESOURCES / DOCUMENT LIBRARY</p><h1>THE<br /><em>RESOURCE</em><br />DESK.</h1><p>Request the information that supports a more informed industrial product or project conversation.</p></section><section className="resource-list">{resources.map(resource => <article key={resource.number}><b>{resource.number}</b><div><p className="eyebrow">IKINOVAC RESOURCE</p><h2>{resource.title}</h2><p>{resource.description}</p></div><Link href={`/contact?resource=${encodeURIComponent(resource.title)}`}>{resource.action} <span>→</span></Link></article>)}</section><section className="resource-linecard"><div><p className="eyebrow light">INDUSTRIAL PRODUCT DIRECTORY</p><h2>All {catalogueCategories.length} categories,<br /><em>one clear starting point.</em></h2><Link href="/products" className="button button-gold">Explore the catalogue <span>→</span></Link></div><ul>{catalogueCategories.slice(0, 8).map(category => <li key={category.slug}>{category.number} / {category.name}</li>)}</ul></section></>;
}

export function ContactPage() {
  const { openQuote } = useRFQ();
  return <><section className="contact-hero" style={{ backgroundImage: `linear-gradient(105deg,rgba(13,23,20,.96),rgba(13,23,20,.5)),url(${assetUrl('/assets/industry/procurement.jpg')})` }}><p className="eyebrow light">PROJECT DESK / REQUEST FOR QUOTE</p><h1>LET&apos;S MAKE<br />THE <em>COMPLEX</em><br />MOVE.</h1><p>Share the essentials of your product, sourcing or project requirement. IKINOVAC will review the correct next step with you.</p></section><section className="contact-page-grid"><div><p className="eyebrow">START HERE</p><h2>A direct engineering <em>enquiry.</em></h2><p>One simple RFQ captures your contact details and requirement. No basket, checkout or technical form is needed before you can speak with the project desk.</p><button className="button button-dark" onClick={() => openQuote()}>Request a quote <span>→</span></button><a href="mailto:info@ikinovac.com" className="text-arrow">info@ikinovac.com <span>↗</span></a><div className="contact-steps"><span><b>01</b> Tell us the requirement</span><span><b>02</b> Submit your RFQ</span><span><b>03</b> Receive IKINOVAC review</span></div></div></section></>;
}
