export const productSystems = [
  { id: 'valves', number: '01', name: 'Valves & Actuation', title: 'Flow control systems', description: 'Valves, actuation and automation systems for critical flow applications.', image: '/assets/industry/valves.jpg', types: ['Ball Valves', 'Gate Valves', 'Control Valves'] },
  { id: 'piping', number: '02', name: 'Piping Products', title: 'Pipe & fitting systems', description: 'Industrial pipe, fittings, flanges and forged connection products.', image: '/assets/industry/refining.jpg', types: ['Seamless Pipes', 'Flanges', 'Forged Fittings'] },
  { id: 'instrumentation', number: '03', name: 'Instrumentation', title: 'Measurement systems', description: 'Pressure, temperature, level and flow measurement solutions.', image: '/assets/industry/instrumentation.jpg', types: ['Pressure Instruments', 'Level Measurement', 'Flow Measurement'] },
  { id: 'equipment', number: '04', name: 'Industrial Equipment', title: 'Process equipment', description: 'Pumps, filtration and industrial equipment for project requirements.', image: '/assets/industry/equipment.jpg', types: ['Pumps', 'Filters', 'Heat Exchangers'] },
  { id: 'procurement', number: '05', name: 'Engineering & Procurement', title: 'Project supply systems', description: 'Project procurement, material coordination and logistics support.', image: '/assets/industry/procurement.jpg', types: ['Project Procurement', 'Inspection', 'Logistics'] }
];

export const industries = [
  { number: '01', name: 'Oil & Gas', detail: 'Flow control, piping and project supply solutions for demanding applications.', image: '/assets/industry/oil-gas.jpg' },
  { number: '02', name: 'Petrochemical & Refining', detail: 'Technical products and procurement coordination for complex process environments.', image: '/assets/industry/refining.jpg' },
  { number: '03', name: 'Power Generation', detail: 'Industrial systems and technical support for power-generation requirements.', image: '/assets/industry/power.jpg' },
  { number: '04', name: 'Marine & Offshore', detail: 'Global supply coordination for demanding marine and offshore operations.', image: '/assets/industry/procurement.jpg' }
];

export const values = [
  { id: 'integrity', number: '01', label: 'Integrity', title: 'INTEGRITY,<br/>ENGINEERED IN.', text: 'We build technical and commercial relationships on transparent communication, accountable coordination and respect for every commitment.', stage: 'FOUNDATION / EVERY PROJECT', image: 'https://images.unsplash.com/photo-1732085251636-221538ac9797?auto=format&fit=crop&w=1600&q=85' },
  { id: 'engineering', number: '02', label: 'Engineering Excellence', title: 'ENGINEERING<br/><span>EXCELLENCE.</span>', text: 'We approach requirements with technical discipline, practical product understanding and a focus on the details that influence project outcomes.', stage: 'TECHNICAL / EVERY REQUIREMENT', image: 'https://images.unsplash.com/photo-1765218933298-dc55fdfb517a?auto=format&fit=crop&w=1600&q=85' },
  { id: 'innovation', number: '03', label: 'Innovation', title: 'THINK FORWARD.<br/><span>STAY PRECISE.</span>', text: 'We keep exploring stronger ways to connect engineering insight, sourcing intelligence and responsive industrial support.', stage: 'PROGRESS / EVERY SOLUTION', image: 'https://images.unsplash.com/photo-1670309178236-d8180b68e2f1?auto=format&fit=crop&w=1600&q=85' },
  { id: 'customer', number: '04', label: 'Customer Commitment', title: 'YOUR PROJECT.<br/><span>IN CLEAR FOCUS.</span>', text: 'We structure support around the actual application, scope, timeline and information needed for a confident decision.', stage: 'PARTNERSHIP / EVERY CONVERSATION', image: 'https://images.unsplash.com/photo-1593617761943-9099951a0769?auto=format&fit=crop&w=1600&q=85' },
  { id: 'quality', number: '05', label: 'Quality', title: 'QUALITY THAT<br/><span>TRAVELS WITH IT.</span>', text: 'Quality requirements, documentation and inspection coordination are considered from the first technical conversation.', stage: 'ASSURANCE / EVERY WORKFLOW', image: 'https://images.unsplash.com/photo-1641293148065-ef450aa0e356?auto=format&fit=crop&w=1600&q=85' },
  { id: 'sustainability', number: '06', label: 'Sustainability', title: 'RESPONSIBLE<br/><span>BY DESIGN.</span>', text: 'We believe disciplined engineering, efficient sourcing and considered delivery choices create more responsible industrial outcomes.', stage: 'RESPONSIBILITY / EVERY DECISION', image: 'https://images.unsplash.com/photo-1630142895963-6996ae6b3a5b?auto=format&fit=crop&w=1600&q=85' },
  { id: 'collaboration', number: '07', label: 'Global Collaboration', title: 'ONE NETWORK.<br/><span>SHARED PURPOSE.</span>', text: 'We bring engineering, commercial and supply perspectives together to make complex industrial requirements easier to progress.', stage: 'CONNECTION / GLOBAL CONTEXT', image: 'https://images.unsplash.com/photo-1578619810395-6b37ba376e11?auto=format&fit=crop&w=1600&q=85' },
  { id: 'improvement', number: '08', label: 'Continuous Improvement', title: 'ALWAYS<br/><span>MOVING FORWARD.</span>', text: 'We learn from every requirement and keep refining the way we support industrial customers and their projects.', stage: 'MOMENTUM / LONG-TERM PARTNERSHIP', image: 'https://images.unsplash.com/photo-1602056820935-316884c035f8?auto=format&fit=crop&w=1600&q=85' }
];
